bot:
  configVersion: '1.2.0'
files:
  foundPair: '/var/random-coffee/static/foundPair.jpeg'
  feedback: '/var/random-coffee/static/feedback.jpeg'
phrases:
  cancelTemplate: "⛔️ Команда {command} отменена"
  firstQuestion: |-

  error: |-
    🙏 Не понимаю
    Воспользуйся /help, чтобы узнать актуальный список доступных тебе команд
  about: |-
    Этот бот — твоя возможность познакомиться с отдыхающими в «Гагаринском» или просто хорошо поболтать за кружечкой кофе.
    Каждый день тебе будет приходить контакт нового человека из лагеря, заинтересованного в общении.
    Создатель @krevedka
    Администраторы: {admins}
  help: |-
    Привет!
    Что-то не работает или нужна помощь?
    Пиши админам(/about)

    🦾 Вот список моих команд
    /help - Поддержим тебя в любой ситуации
    /about - О боте
    /stop - Приостановить участие
    /show_info - показать информацию о текущем аккаунте
    /edit - Изменить учётную запись
    /status - Статус текущей встречи
  start: |-
    Привет!
    Этот бот — твоя возможность познакомиться с отдыхающими в лагере «Гагаринский», спросить совета или просто хорошо поболтать. ☕️
    Каждый день тебе будет приходить контакт нового человека из сообщества, заинтересованного в общении.
    
    Для начала ответь на несколько вопросов о себе
  sucessStart: |-
    Для начала ответь на несколько вопросов о себе

    Как тебя зовут?
  firstEditSquad: |-
    Из какого ты отряда?
  firstEditAbout: |-
    Расскажи о себе: чем занимаешься, какие есть хобби или любую другую информацию, которую считаешь интересной.

    Так твой будущий друг сможет лучше узнать тебя до встречи.
  currentData: |-
    😎 Твои текущие данные:
      Имя: {{ name }}
      Отряд: {{ squad }}
      О себе: {{ about }}
      Nick в тг: @{{ nickname }}

    Для обновления используй команду /edit
    Если тебе нужна помощь напиши в чат /help
  adminCurrentData: |-

    😎 Данные пользователя:
      ID: {{ id }}
      Заблокирован: {{ is_banned }}
      Дата регистрации: {{ register_date }}
      Администратор: {{ is_admin }}
      Имя: {{ name }}
      Отряд: {{ squad }}
      О себе: {{ about }}
      Nick в тг: @{{ nickname }}
  edit: "Выбери что ты хочешь изменить?"
  changeNameText: "Введи новое имя или используй команду /cancel"
  changeAboutText: "Расскажи что-нибудь о себе или используй команду /cancel"
  changeSquadText: "Укажи свой отряд или используй команду /cancel"
  changeNicknameText: "Твой никнейм обновлён. Желаешь изменить что-нибудь еще?"
  changeSuccess: "Данные обновлены. Желаешь изменить что-нибудь еще?"
  stopText: "Очень жаль! Если захочешь вернуться, напиши мне /start"
  statusText: "Твой собеседник на сегодня @{nickname}"
  statusTextError: "Ой! Собеседник еще не найден! Не переживай, завтра я постараюсь кого-нибудь найти"
  pairFound: |-
    Привет! 👋
    Твоя компания для кофе на сегодня:
        Имя: {name}
        Отряд: {squad}
        Инфо: {about}

    Напиши первым, чтобы назначить встречу 👉🏻 @{nickname}
  feedBack: |-
    Привет!
    Расскажи, получилось ли встретиться с @{nickname} ?
  feedBackSuccessButton: "Да, всё получилось"
  feedBackFailedButton: "Нет"
  feedBackNotSureButton: "Затрудняюсь ответить"
  feedBackSended: "Спасибо за обратную с связь!"

  noneInfo: "Не указано"
  noneAbout: "Пользователь пока не указал информацию о себе, может быть ты сможешь узнать его получше?"
  noneSquad: "Пользователь не указал свой отряд, напиши ему и узнай как его найти 🧐"
  noneName: "Пользователь предпочел не указаывать своё имя, напиши ему и узнай как его найти 🧐"
  noneNickname: "Пожалуйста, укажи свой никнейм в телеграме, чтобы твой собеседник мог тебя найти 😊"
  noneNicknameUpdate: "Пожалуйста, укажи свой никнейм в телеграме, чтобы твой собеседник мог тебя найти, a затем воспольузуйся командой /edit"

  #admin Section
  banSuccess: "Пользователь заблокирован"
  unbanSuccess: "Пользователь разблокирован"
  editError: "Не удалось поменять статус пользователя"

  userBanned: |-
    Пользователь заблокирован.
    По вопросам разблокировки обратитесь к админстраторам: {admins}
  adminPanel: |-
    Выберите действие
  adminEnterNickname: |-
    Введите никнейм пользователя
  adminUserNotFound: |-
    Пользователь не найден
buttons:
  #feedback menu
  feedBackSuccess:
    label:  "Да, всё получилось"
    id: "FEEDBACK_SUCCESS"
  feedBackFailed:
    label: "Нет"
    id: "FEEDBACK_FAILED"
  feedBackNotSure:
    label: "Затрудняюсь ответить"
    id: "FEEDBACK_NOT_SURE"
  start:
    label: "Поехали 🚀"
    id: "START_EDIT"
  cancel:
    label: "Отменить команду"
    id: "CANCEL"
  #edit menu
  changeName:
    label: "Имя"
    id: "CHANGE_NAME"
  changeAbout:
    label: "О себе"
    id: "CHANGE_ABOUT"
  changeSquad:
    label: "Отряд"
    id: "CHANGE_SQUAD"
  changeNickname:
    label: "Ник в телеграме"
    id: "CHANGE_NICKNAME"
  #help menu
  help:
    label: "Помощь"
    id: "HELP"
  about:
    label: "О боте, связь с админами"
    id: "ABOUT"
  showInfo:
    label: "Показать твою информацию"
    id: "SHOW_INFO"
  edit:
    label: "Изменить информацию о себе"
    id: "EDIT"
  status:
    label: "Показать сегодняшнего собеседника"
    id: "STATUS"
  stop:
    label: "Приостановить участие"
    id: "STOP"
  hideButtons:
    label: "Скрыть меню"
    id: "HIDE_BUTTONS"
  back:
    label: "Назад"
    id: "BACK"
  adminShowUsers:
    label: "Список пользователей"
    id: "ADMIN_SHOW_USERS"
  adminShowMoreUsers:
    label: "Загрузить еще"
    id: "ADMIN_SHOW_MORE_USERS"
  adminShowInfo:
    label: "Информация о участнике"
    id: "ADMIN_SHOW_INFO"
  adminBanUser:
    label: "Заблокировать"
    id: "ADMIN_BAN_USER"
  adminUnbanUser:
    label: "Разблокировать"
    id: "ADMIN_UNBAN_USER"